### ISSUE TITLE
why there is <link as="script" href="/nuxt/other.legacy"/>

### ISSUE THREAD

**Issue by yinyanli** [IlyaSemenov/nuxt-vite-legacy#10]
Following your steps, the entry.legacy.js can be removed successfully, but I don’t know why there is <link as="script" href="/nuxt/other.legacy"/>

**Comment by IlyaSemenov** [comment]
entry-legacy.js contains the legacy build of the Vue app core (Nuxt, Vue and other deps such as oftech or ufo) for legacy browsers. It can only be "successfully removed" on modern browsers.

If you don't need legacy chunks, you can disable them with `legacy: { renderLegacyChunks: false }`.
