### ISSUE TITLE
Issue with Loading JavaScript in Nuxt 3 App on Chromium 49

### ISSUE THREAD

**Issue by gkikillai** [IlyaSemenov/nuxt-vite-legacy#11]
Hi there,

I've been trying to use your plugin for my personal project, as it is necessary for my Nuxt 3 app to work under Chrome 49. I downloaded Chromium version 49 (Version 49.0.2623.23 (64-bit)) for this purpose. I attempted to launch the playground in the repository using this version, but the JavaScript files are not loading. This issue occurs both in dev mode and build mode. Any insights into what might be causing this problem?

Thanks!

Chromium 49:
![image](https://github.com/IlyaSemenov/nuxt-vite-legacy/assets/126081518/e293e9f3-5c68-4d05-9944-994d70fbdddb)

Current Chrome:
![image](https://github.com/IlyaSemenov/nuxt-vite-legacy/assets/126081518/e8c81281-07ed-48bf-b33f-681c1d3b2f71)

**Comment by IlyaSemenov** [comment]
You're trying it in dev mode, where it's not supposed to work. If you run the steps outlined in "Development and Testing" section verbatim, it will work (more or less so):

<img width="818" alt="image" src="https://github.com/IlyaSemenov/nuxt-vite-legacy/assets/128121/cef649b6-7ee4-4b25-9359-8060d48e66f9">

**Comment by gkikillai** [comment]
Hi Ilya,

I tried it anyway, but the following error occurs in the browser and the page does not loading.
OS: Windows 11, Chromium 49

![image](https://github.com/IlyaSemenov/nuxt-vite-legacy/assets/126081518/9e05ca2b-68c9-43c1-8c31-2b88b9f9864c)

Do you have any ideas for this?

**Comment by IlyaSemenov** [comment]
No, not a clue. This probably has something to do with Chromium itself. Can it load anything else?

I have a relatively extensive SaaS (100+ heavily scripted pages) which runs fine on Windows XP / Chrome 49 clients with this module. These are however actual native Google Chromes (same as on my screenshot above), not Chromium builds.

**Comment by gkikillai** [comment]
I have a Set-top-box, and there runs Chrome 49 engine, I wanted to try, but I couldn't generate production (npm run generate), because there was an error:
Nuxt Build Error: [vite]: Rollup failed to resolve import "mdn-polyfills/Element.prototype.getAttributeNames" from "vite/legacy-polyfills".
This is most likely unintended because it can break your application at runtime.
If you do want to externalize this module explicitly add it to
build.rollupOptions.external

This is most likely unintended because it can break your application at runtime.
If you do want to externalize this module explicitly add it to
build.rollupOptions.external

This is a single start project from nuxt 3 (npx nuxi@latest init text-legacy), and I added your plugin for this project.

Do you have any idea from that?

**Comment by IlyaSemenov** [comment]
It looks like you didn't install the polyfill that you intended to use.

Run:

```
npm i --save-dev mdn-polyfills
```

**Comment by IlyaSemenov** [comment]
Closing due to lack of feedback, and probably a non-problem.
