### ISSUE TITLE
Not working on static website

### ISSUE THREAD

**Issue by ztgame-website-fe** [IlyaSemenov/nuxt-vite-legacy#12]
Hi there,

I've been trying to use your plugin for project created by vitesse-nuxt3. I generated the static web site and hosted it with http-server. It doesn't work on chrome 60 while it's ok above chrome66. Any insights into what might be causing this problem? Below is my nuxt.config: 

```javascript
modules: [
    '@vueuse/nuxt',
    '@unocss/nuxt',
    '@pinia/nuxt',
    '@nuxtjs/color-mode',
    'nuxt-module-eslint-config',
    'nuxt-vite-legacy'
  ],
  legacy: {
    targets: ["chrome 49"],
    additionalLegacyPolyfills: [
      "mdn-polyfills/Element.prototype.getAttributeNames",
    ],
    modernPolyfills: [
      'es.global-this',
      'es/object',
      'es/array',
      'es.symbol',
      'es.array.filter',
      'es.promise',
      'es.promise.finally',
      'es/map',
      'es/set',
      'es.array.from',
      'es.array.for-each',
      'es.object.define-properties',
      'es.object.define-property',
      'es.object.get-own-property-descriptor',
      'es.object.get-own-property-descriptors',
      'es.object.keys',
      'es.object.to-string',
      'web.dom-collections.for-each',
      'esnext.global-this',
      'esnext.string.match-all',
      'es.object.define-setter',
      'es.array.iterator',
      'es.object.assign',
      'es.array.includes'
    ],
  },
```

Thanks!

![image](https://github.com/IlyaSemenov/nuxt-vite-legacy/assets/63392481/4bf78c9f-10c1-4a7c-8860-4e6c1e2f16c4)

**Comment by jayxuz** [comment]
I got the same issue.
I change the "nuxt" npm version to 3.7.4 and fix it. 
you can try it.

But I also want this issue can be fixed.

**Comment by ztgame-website-fe** [comment]
> I got the same issue. I change the "nuxt" npm version to 3.7.4 and fix it. you can try it.
> 
> But I also want this issue can be fixed.

Great! It works. Do you know how to fix the style compability?
![image](https://github.com/IlyaSemenov/nuxt-vite-legacy/assets/63392481/661aa61c-79f4-4411-a08c-a866c8fdd1c3)

It should like below:
![image](https://github.com/IlyaSemenov/nuxt-vite-legacy/assets/63392481/88081b24-7c87-423f-a687-dab92c27a61f)

**Comment by IlyaSemenov** [comment]
Honestly, I never tested this with static websites. This module relies on a runtime nitro plugin:

https://github.com/IlyaSemenov/nuxt-vite-legacy/blob/c98e1dbf9f00cfce9990d6ca753edc45a6f0e0ca/src/runtime/server-plugin.ts#L3-L6

but I don't know if it's even called during prerendering...

I'll try to see when I have time; also, PR's welcome.

**Comment by IlyaSemenov** [comment]
Perhaps #13 is the same problem.

**Comment by ztgame-website-fe** [comment]
> Perhaps #13 is the same problem.

Actually it works very well above chrome 66，thanks a lot for your plugin. I don't know if it also points to old version below 66.

**Comment by jayxuz** [comment]
> Honestly, I never tested this with static websites. This module relies on a runtime nitro plugin:
> 
> https://github.com/IlyaSemenov/nuxt-vite-legacy/blob/c98e1dbf9f00cfce9990d6ca753edc45a6f0e0ca/src/runtime/server-plugin.ts#L3-L6
> 
> but I don't know if it's even called during prerendering...
> 
> I'll try to see when I have time; also, PR's welcome.

In fact, I also encountered this problem when accessing with Chrome 55 in SSR mode. The main reason is that during page pre-rendering, it requests JSON from the meta folder, but the fetch request method is undefined, leading to the failure of the request. However, when I changed Nuxt to version 3.7.4, accessing in SSR mode worked normally.



> > I got the same issue. I change the "nuxt" npm version to 3.7.4 and fix it. you can try it.
> > But I also want this issue can be fixed.
> 
> Great! It works. Do you know how to fix the style compability? ![image](https://private-user-images.githubusercontent.com/63392481/301797932-661aa61c-79f4-4411-a08c-a866c8fdd1c3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY5MjM3ODIsIm5iZiI6MTcwNjkyMzQ4MiwicGF0aCI6Ii82MzM5MjQ4MS8zMDE3OTc5MzItNjYxYWE2MWMtNzlmNC00NDExLWEwOGMtYTg2NmM4ZmRkMWMzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjAzVDAxMjQ0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY5YTY3MTY1ZjFkYTdhYjBhNjRiYmI2ZjRjODliZjk1MDY3MWM3Mzk1MTc4MGQxNzI2MTY2ZGEwNDk0NmNhMzkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.oDzu6sunZPQUB2hjyKN8id4DRCp5zNQtTeBPxrVi-GM)
> 
> It should like below: ![image](https://private-user-images.githubusercontent.com/63392481/301798326-88081b24-7c87-423f-a687-dab92c27a61f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY5MjM3ODIsIm5iZiI6MTcwNjkyMzQ4MiwicGF0aCI6Ii82MzM5MjQ4MS8zMDE3OTgzMjYtODgwODFiMjQtN2M4Ny00MjNmLWE2ODctZGFiOTJjMjdhNjFmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjAzVDAxMjQ0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ0M2EzMjljZjZiNjhjMTRiM2YzMzgyNmQ4MWNkYTlkYzBlMjI0MDliMzk4YTVkZWQ5ZjFiODI3Njk4ZDJiNjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.rJHGQHCwO-0VmuH9TTb-u1qYCT-mW8_LMRV5fg6E53o)

Additionally, regarding the conversion issue with older CSS versions, it's true that style errors can occur due to old browsers not supporting new CSS methods. For now, I don't know of any solution, so the only option is to minimize the use of advanced syntax in the source code to maximize CSS compatibility.

**Comment by ztgame-website-fe** [comment]
> > Honestly, I never tested this with static websites. This module relies on a runtime nitro plugin:
> > https://github.com/IlyaSemenov/nuxt-vite-legacy/blob/c98e1dbf9f00cfce9990d6ca753edc45a6f0e0ca/src/runtime/server-plugin.ts#L3-L6
> > 
> > but I don't know if it's even called during prerendering...
> > I'll try to see when I have time; also, PR's welcome.
> 
> In fact, I also encountered this problem when accessing with Chrome 55 in SSR mode. The main reason is that during page pre-rendering, it requests JSON from the meta folder, but the fetch request method is undefined, leading to the failure of the request. However, when I changed Nuxt to version 3.7.4, accessing in SSR mode worked normally.
> 
> > > I got the same issue. I change the "nuxt" npm version to 3.7.4 and fix it. you can try it.
> > > But I also want this issue can be fixed.
> > 
> > 
> > Great! It works. Do you know how to fix the style compability? ![image](https://private-user-images.githubusercontent.com/63392481/301797932-661aa61c-79f4-4411-a08c-a866c8fdd1c3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY5MjM3ODIsIm5iZiI6MTcwNjkyMzQ4MiwicGF0aCI6Ii82MzM5MjQ4MS8zMDE3OTc5MzItNjYxYWE2MWMtNzlmNC00NDExLWEwOGMtYTg2NmM4ZmRkMWMzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjAzVDAxMjQ0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY5YTY3MTY1ZjFkYTdhYjBhNjRiYmI2ZjRjODliZjk1MDY3MWM3Mzk1MTc4MGQxNzI2MTY2ZGEwNDk0NmNhMzkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.oDzu6sunZPQUB2hjyKN8id4DRCp5zNQtTeBPxrVi-GM)
> > It should like below: ![image](https://private-user-images.githubusercontent.com/63392481/301798326-88081b24-7c87-423f-a687-dab92c27a61f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY5MjM3ODIsIm5iZiI6MTcwNjkyMzQ4MiwicGF0aCI6Ii82MzM5MjQ4MS8zMDE3OTgzMjYtODgwODFiMjQtN2M4Ny00MjNmLWE2ODctZGFiOTJjMjdhNjFmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjAzVDAxMjQ0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ0M2EzMjljZjZiNjhjMTRiM2YzMzgyNmQ4MWNkYTlkYzBlMjI0MDliMzk4YTVkZWQ5ZjFiODI3Njk4ZDJiNjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.rJHGQHCwO-0VmuH9TTb-u1qYCT-mW8_LMRV5fg6E53o)
> 
> Additionally, regarding the conversion issue with older CSS versions, it's true that style errors can occur due to old browsers not supporting new CSS methods. For now, I don't know of any solution, so the only option is to minimize the use of advanced syntax in the source code to maximize CSS compatibility.

OK. Appreciate for your answer.

**Comment by ztgame-website-fe** [comment]
> > Honestly, I never tested this with static websites. This module relies on a runtime nitro plugin:
> > https://github.com/IlyaSemenov/nuxt-vite-legacy/blob/c98e1dbf9f00cfce9990d6ca753edc45a6f0e0ca/src/runtime/server-plugin.ts#L3-L6
> > 
> > but I don't know if it's even called during prerendering...
> > I'll try to see when I have time; also, PR's welcome.
> 
> In fact, I also encountered this problem when accessing with Chrome 55 in SSR mode. The main reason is that during page pre-rendering, it requests JSON from the meta folder, but the fetch request method is undefined, leading to the failure of the request. However, when I changed Nuxt to version 3.7.4, accessing in SSR mode worked normally.
> 
> > > I got the same issue. I change the "nuxt" npm version to 3.7.4 and fix it. you can try it.
> > > But I also want this issue can be fixed.
> > 
> > 
> > Great! It works. Do you know how to fix the style compability? ![image](https://private-user-images.githubusercontent.com/63392481/301797932-661aa61c-79f4-4411-a08c-a866c8fdd1c3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY5MjM3ODIsIm5iZiI6MTcwNjkyMzQ4MiwicGF0aCI6Ii82MzM5MjQ4MS8zMDE3OTc5MzItNjYxYWE2MWMtNzlmNC00NDExLWEwOGMtYTg2NmM4ZmRkMWMzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjAzVDAxMjQ0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY5YTY3MTY1ZjFkYTdhYjBhNjRiYmI2ZjRjODliZjk1MDY3MWM3Mzk1MTc4MGQxNzI2MTY2ZGEwNDk0NmNhMzkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.oDzu6sunZPQUB2hjyKN8id4DRCp5zNQtTeBPxrVi-GM)
> > It should like below: ![image](https://private-user-images.githubusercontent.com/63392481/301798326-88081b24-7c87-423f-a687-dab92c27a61f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY5MjM3ODIsIm5iZiI6MTcwNjkyMzQ4MiwicGF0aCI6Ii82MzM5MjQ4MS8zMDE3OTgzMjYtODgwODFiMjQtN2M4Ny00MjNmLWE2ODctZGFiOTJjMjdhNjFmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjAzVDAxMjQ0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ0M2EzMjljZjZiNjhjMTRiM2YzMzgyNmQ4MWNkYTlkYzBlMjI0MDliMzk4YTVkZWQ5ZjFiODI3Njk4ZDJiNjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.rJHGQHCwO-0VmuH9TTb-u1qYCT-mW8_LMRV5fg6E53o)
> 
> Additionally, regarding the conversion issue with older CSS versions, it's true that style errors can occur due to old browsers not supporting new CSS methods. For now, I don't know of any solution, so the only option is to minimize the use of advanced syntax in the source code to maximize CSS compatibility.

OK. Appreciate for your answer.

**Comment by lightglitch** [comment]
You can disable app manifest generation in nuxt:

https://nuxt.com/blog/v3-8#app-manifest

In that case the meta json files are not generated.

**Comment by IlyaSemenov** [comment]
Guys, I just tried unmodified playground of this repo:

```
pnpm nuxi generate playground
pnpx serve playground/.output/public
```

and it worked:

<img width="1048" alt="image" src="https://github.com/IlyaSemenov/nuxt-vite-legacy/assets/128121/29177b50-f607-4b81-b84b-ba57bf366dc2">

Even though it printed a few error messages about the manifest, the scripts loaded and the Vue app was functioning.

Can anyone please come up with a reproduction of a failing app?

**Comment by jayxuz** [comment]
> You can disable app manifest generation in nuxt:
> 
> https://nuxt.com/blog/v3-8#app-manifest
> 
> In that case the meta json files are not generated.


I tried turning off the appManifest option and then rebuilding. Lower versions of Chrome can now access it normally, and the functionality is basically normal. This method is indeed useful.
Thank you！

**Comment by ztgame-website-fe** [comment]
> You can disable app manifest generation in nuxt:
> 
> https://nuxt.com/blog/v3-8#app-manifest
> 
> In that case the meta json files are not generated.

It works! Thanks a lot.
