### ISSUE TITLE
Support for Nuxt generate?

### ISSUE THREAD

**Issue by lightglitch** [IlyaSemenov/nuxt-vite-legacy#13]
Does your module works with static generation websites?

Because we just try it with a demo of ours and the generated html in public folder didn't change at all.

Than you

**Comment by lightglitch** [comment]
closed in favor of #12

**Comment by IlyaSemenov** [comment]
@lightglitch Can you come up with a demo site that doesn't work? See #12, I tested site generation on a playground in this repo and it worked for me.
