### ISSUE TITLE
ts type error: 类型实例化过深，且可能无限。ts(2589)

### ISSUE THREAD

**Issue by xuxchao** [IlyaSemenov/nuxt-vite-legacy#14]
![image](https://github.com/IlyaSemenov/nuxt-vite-legacy/assets/28293069/14c0bd3a-72f6-434b-b771-608fbc6e9a86)

**Comment by IlyaSemenov** [comment]
សូមកុំប្រើនិមិត្តសញ្ញាចិន មនុស្សភាគច្រើនលើពិភពលោកមិនយល់ពីវា
