### ISSUE TITLE
打包之后出现entry-legacy.5ff2d4a8.js:1 Uncaught ReferenceError: System is not defined     at entry-legacy.5ff2d4a8.js:1

### ISSUE THREAD

**Issue by ReginYuan** [IlyaSemenov/nuxt-vite-legacy#4]

**Comment by IlyaSemenov** [comment]
This could have been caused by Nuxt emitting slightly different HTML, and the module failing to apply the fixes.

Will you be able to come up with a reproduction at StackBlitz?

**Comment by IlyaSemenov** [comment]
I see that Nuxt had recent updates in emitting HTML tags: https://github.com/nuxt-contrib/vue-bundle-renderer/issues/48 so this is quite probable. I will test with the latest Nuxt.

**Comment by IlyaSemenov** [comment]
I tried with Nuxt 3.7.4 and it worked almost fine (the module didn't remove legacy prefetch links due to the above changes, but the actual legacy build was functioning).

Please come up with a reproduction repo.

**Comment by IlyaSemenov** [comment]
The playground in the project works in Nuxt 3.4 through 3.8. I fixed the legacy prefetch removing regexp but that was really only a performance/extra warnings problem, it didn't lead to the error in question.

Feel free to reopen if you have a proper reproduction that I can run.

Also, please update the title to not include the cryptic hieroglyphs, people don't speak those all over the world.
